import numpy as np


def validate_solution(solution, correct_solution, relative_threshold=0.05):
    """Validates the student's solution against the correct solution.

    This function compares the student's solution with the correct solution at each time step.
    If the difference between the two solutions is within the specified threshold, the solution
    is considered valid.

    Args:
        solution (numpy.ndarray): The solution generated by the student's implementation.
        correct_solution (numpy.ndarray): The solution generated by the correct implementation.
        relative_threshold (float): The allowable difference between the two solutions at any time
            step indicated in percentage (decimal). Defaults to 0.05.

    Returns:
        bool: True if the student's solution is within the threshold of the correct solution,
                False otherwise.
    """
    # check if shape of solutions match
    if solution.shape != correct_solution.shape:
        print("Error: Your solution and the correct solution have different shapes.")
        return False

    # if solutions are equal, return True
    if np.array_equal(solution, correct_solution, equal_nan=False):
        print("Yor solution is correct!")
        return True

    # if solutions are not equal, compare solutions at each time step
    # if relative error is within threshold, consider the solution correct
    for j in range(len(solution)):
        # avoid division by zero for very small correct_solution values
        if abs(correct_solution[j]) < 1e-10:
            if abs(solution[j] - correct_solution[j]) > 1e-10:
                print(f"Solution mismatch at time step {j}.")
                print(f"Yours: {solution[j]}, Correct: {correct_solution[j]}")
                return False
        else:
            relative_error = abs(
                (solution[j] - correct_solution[j]) / correct_solution[j]
            )
            if relative_error > relative_threshold:
                print(f"Solution mismatch at time step {j}.")
                print(
                    f"Yours: {solution[j]}, Correct: {correct_solution[j]}, Relative Error: {relative_error}"
                )
                return False

    # If all checks pass, the solution is valid
    print("Yor solution is correct!")
    return True
